#
# The following #defines are for NetBSD contributed by Mark Davies,
# Victoria University of Wellington, NZ   <mark@mcs.vuw.ac.nz>, 15 Aug 2001.
#
INCLUDES	=
#
XINCLUDES	= -I/usr/pkg/include -I/usr/X11R6/include
XLIBS		= -ltcl83 -ltk83 -lX11 -lm
#
CFLAGS		= -O $(INCLUDES) $(XINCLUDES)
C99		= gcc -std=c99 -pedantic -Wall

LD		= gcc -rdynamic
LDFLAGS		=

LIBDIRS		= -L/usr/pkg/lib -L/usr/X11R6/lib -Wl,-R/usr/pkg/lib:/usr/X11R6/lib
LIBS		= -lm
STRIP		= strip


include	Makefile.common
