
clean:
	cd click && make clean
	cd flooding && make clean
	cd keyboard && make clean
	cd leds && make clean
	cd linkstate && make clean
	cd stopandwait && make clean
	cd ticktock && make clean
	cd wlan && make clean
	@rm -rf f? *.o *.cnet */*.o */*.cnet

